
format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[ðŸžˆ](#c0c5cd bold)"
error_symbol = "[ðŸžˆ](#354753)"
vicmd_symbol = "[ðŸžˆ](#515B69)"

[directory]
format = "[î‚¶]($style)[(bg:#354753 fg:#515B69)$path](bg:#354753 fg:#c0c5cd)[î‚´ ]($style)"
style = "fg:#354753"

[git_branch]
format = "[î‚¶]($style)[[ï‡“ ](bg:#354753 fg:#c0c5cd bold)$branch](bg:#354753 fg:#515B69)[î‚´ ]($style)"
style = "fg:#354753"
