
format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[ðŸžˆ](#cd9fc0 bold)"
error_symbol = "[ðŸžˆ](#5A5D62)"
vicmd_symbol = "[ðŸžˆ](#BA4546)"

[directory]
format = "[î‚¶]($style)[(bg:#5A5D62 fg:#BA4546)$path](bg:#5A5D62 fg:#cd9fc0)[î‚´ ]($style)"
style = "fg:#5A5D62"

[git_branch]
format = "[î‚¶]($style)[[ï‡“ ](bg:#5A5D62 fg:#cd9fc0 bold)$branch](bg:#5A5D62 fg:#BA4546)[î‚´ ]($style)"
style = "fg:#5A5D62"
