
format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[ðŸžˆ](#d3d5d9 bold)"
error_symbol = "[ðŸžˆ](#535E5C)"
vicmd_symbol = "[ðŸžˆ](#C7543C)"

[directory]
format = "[î‚¶]($style)[(bg:#535E5C fg:#C7543C)$path](bg:#535E5C fg:#d3d5d9)[î‚´ ]($style)"
style = "fg:#535E5C"

[git_branch]
format = "[î‚¶]($style)[[ï‡“ ](bg:#535E5C fg:#d3d5d9 bold)$branch](bg:#535E5C fg:#C7543C)[î‚´ ]($style)"
style = "fg:#535E5C"
