
format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[ðŸžˆ](#cbdad9 bold)"
error_symbol = "[ðŸžˆ](#7BA39C)"
vicmd_symbol = "[ðŸžˆ](#92AFAA)"

[directory]
format = "[î‚¶]($style)[(bg:#7BA39C fg:#92AFAA)$path](bg:#7BA39C fg:#cbdad9)[î‚´ ]($style)"
style = "fg:#7BA39C"

[git_branch]
format = "[î‚¶]($style)[[ï‡“ ](bg:#7BA39C fg:#cbdad9 bold)$branch](bg:#7BA39C fg:#92AFAA)[î‚´ ]($style)"
style = "fg:#7BA39C"
