
format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[ðŸžˆ](#1C1F2E bold)"
error_symbol = "[ðŸžˆ](#4F7AC1)"
vicmd_symbol = "[ðŸžˆ](#3F81BD)"

[directory]
format = "[î‚¶]($style)[(bg:#4F7AC1 fg:#3F81BD)$path](bg:#4F7AC1 fg:#1C1F2E)[î‚´ ]($style)"
style = "fg:#4F7AC1"

[git_branch]
format = "[î‚¶]($style)[[ï‡“ ](bg:#4F7AC1 fg:#1C1F2E bold)$branch](bg:#4F7AC1 fg:#3F81BD)[î‚´ ]($style)"
style = "fg:#4F7AC1"
